### ISSUE TITLE
Strange assert error 

### ISSUE THREAD

**Issue by sagesimhon** [mitsuba-renderer/drjit-core#63]
Hello, I am using 'llvm_ad_rgb' variant on a linux box with /usr/lib64/libLLVM-15.0.6.so installed, and I randomly get this fatal error:

Assertion failed in /project/ext/drjit-core/ext/nanothread/src/queue.cpp:354: remain == 1

No info or stack trace. Any ideas how to resolve?

**Comment by merlinND** [comment]
Hello @sagesimhon,

Could you please post a more complete description of your setup in the following issue (how Mitsuba was installed, what code are you running, etc): https://github.com/mitsuba-renderer/mitsuba3/issues/190

**Comment by basit-7** [comment]
Hi @merlinND, I faced the same issue while running the animation script (anim_obj_axis.py) from [this](https://github.com/OuyangJunyuan/PointCloudRenderer) repo. I followed the instruction for setting up the environment from the repo, it uses mitsuba3.

**Comment by sagesimhon** [comment]
Hi 

This his becoming a bigger issue for me. Apologies I have not responded as I was running alternatives that I can no longer do. I will post more info on #190

**Comment by njroussel** [comment]
I'll close this, we'll track it over here: https://github.com/mitsuba-renderer/mitsuba3/issues/849
