### ISSUE TITLE
Migration from host to device should use the pinned data copy

### ISSUE THREAD

**Issue by futscdav** [mitsuba-renderer/drjit-core#73]
Noticed this while going through some details on memory management:

https://github.com/mitsuba-renderer/drjit-core/blob/2eb6005f4085898b4c69f361057c7e90254bf422/src/malloc.cpp#L333-L338

The intention was likely to read from the pinned data copy, not from the original data.

**Comment by wjakob** [comment]
Oof, that's not good. I think we may be saved by `cuMemcpyAsync` here, which downgrades to a sync copy when the source buffer is not pinned. Fixed in https://github.com/mitsuba-renderer/drjit-core/commit/e51750e44d79ddeefe548c8942ceaf0c2daff36d
