### ISSUE TITLE
Scope ordering problems in multi-threading applications

### ISSUE THREAD

**Issue by DoeringChristian** [mitsuba-renderer/drjit-core#79]
Hi,

I'm not sure if multi-threading is in the scope of the project but as there is a lot of focus put on synchronization by adding a mutex I thought it might be.

In some scenarios, the scope order might be incorrect.
Since every thread has their own current scope in a thread-local variable (`ThreadState.scope`), situations might occur where a variables scope id is less than it's dependencies.
Since the variables/operations are reordered according to their scope in a kernel, this might result in them reading values that are uninitialized.
This effectively destroys the topological order of the variables.
The following is a somewhat contrived example, but one could imagine recording a loop in a different thread, which increments the global scope.

```cpp
TEST_BOTH(11_threading) {
    jit_set_log_level_stderr(LogLevel::Trace);
    
    UInt32 x = opaque<UInt32>(1, 2);

    UInt32 y;
    auto yp = &y;
    printf("\n");
    printf("Scope of thread 1: %d\n", jit_scope(Backend));

    std::thread t([=](){
        jit_new_scope(Backend);
        printf("Scope of thread 2: %d\n", jit_scope(Backend));
        *yp = opaque<UInt32>(1, 2);
    });

    t.join();

    printf("Scope of thread 1: %d\n", jit_scope(Backend));
    
    UInt32 z = x + y;
    jit_var_schedule(z.index());
    jit_eval();
    
    printf("%s\n", z.str());
    jit_assert(strcmp(z.str(), "[2, 2]")== 0);
}

```
Here, the scope is explicitly incremented in a different thread and the variable `y` will "inherit" the current scope in `t`.
Therefore the scope of variable `x` will be less than the one of variable `y`.
The current scope of thread 1 stays the same and therefore the scope of variable `z` will be the same as `x`, which is lower than that of `y`.
When compiling the kernel, Dr.Jit will reorder operations according to their scope with the assumption that this will not break the order from the topology sort performed previously.
Therefore the body of the kernel in CUDA looks something like this (I added comments):
```ptx
body: // sm_86
    // x is loaded
    ld.param.u64 %rd0, [params+8];
    mad.wide.u32 %rd0, %r0, 4, %rd0;
    ld.global.cs.u32 %r4, [%rd0];

    // x and (not yet loaded) y are added to produce z
    add.u32 %r5, %r4, %r6;

    // z is stored
    ld.param.u64 %rd0, [params+16];
    mad.wide.u32 %rd0, %r0, 4, %rd0;
    st.global.cs.u32 [%rd0], %r5;

    // y is loaded after z has already been stored
    ld.param.u64 %rd0, [params+24];
    mad.wide.u32 %rd0, %r0, 4, %rd0;
    ld.global.cs.u32 %r6, [%rd0];

    add.u32 %r0, %r0, %r1;
    setp.ge.u32 %p0, %r0, %r2;
    @!%p0 bra body;

done:
```

**Comment by njroussel** [comment]
Hi @DoeringChristian 

I think we are aware of this behavior. The solution has been to build a new scope after joining your threads. 

I believe we only use this scoping feature in Mitsuba's parallel scene loader. If you take a look at this snippet: https://github.com/mitsuba-renderer/mitsuba3/blob/8bab68b6cec812d27b5e60474a5457c7b6b5f7eb/src/core/xml.cpp#L1172-L1181
We create a new  scope counter for the main thread after the root node has been constructed. This is semantically equivalent to creating a new scope after you've joined all your threads.

I'm not sure if this is a satisfying answer ?

**Comment by DoeringChristian** [comment]
Thanks for the quick response!

Do you think it would make sense to resolve the scope automatically in such cases or would the overhead be to big?

As I only wanted to bring this to your attention, but you are already aware of it I think the issue is more or less resolved.

**Comment by njroussel** [comment]
Sorry I lost track of this.

> Do you think it would make sense to resolve the scope automatically in such cases or would the overhead be to big?

Yeah, I think this would be too much of an overhead. We should provide better utilities to handle this for users - like a context manager of some sort.
