### ISSUE TITLE
having problems with masking

### ISSUE THREAD

**Issue by toaster-robotics** [mitsuba-renderer/drjit-core#90]
Hello, I'm having trouble with simple masking of arrays. I'm sure I'm doing something dumb but just can't figure it out. I'm working with a larger array but I have created a simple example to show what the issue is. I'm expecting **[0.0, 1.0, 2.0, 4.0]** here. This is how I'm use to doing masking in numpy/torch and it's also how it's done in the [Scripting a renderer example](https://mitsuba.readthedocs.io/en/latest/src/rendering/scripting_renderer.html) (`result[~scene.ray_test(ray_2)] += 1.0`)

![Screenshot from 2024-05-24 15-09-58](https://github.com/mitsuba-renderer/drjit-core/assets/141705577/04cddf67-91e3-45df-b447-84bf229d8777)

**Comment by merlinND** [comment]
Hello @toaster-robotics,

In DrJit, this kind of masking syntax can be used during assignment:

```py
a[mask] = -1.0
```

but not as indexing. If you would like to get a smaller array with only the entries for which `mask == True`, have a look at [`dr.compress()`](https://drjit.readthedocs.io/en/latest/reference.html#drjit.compress) or [`dr.scatter_inc()`](https://drjit.readthedocs.io/en/latest/reference.html#drjit.scatter_inc).
